require_relative '../node_modules/react-native-test-app/macos/test_app'

workspace 'MenuExample.xcworkspace'

use_test_app! do |target|
    target.app do
        pod 'react-native-menu', :path => '../../react-native-menu.podspec'
    end
end
